{% set name = "lazy_loader" %}
{% set version = "0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 0edc7a5175c400acb108f283749951fefdadedeb00adcec6e88b974a9254f18a

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
    - flit-core 3.8.0
  run:
    - python

test:
  imports:
    - lazy_loader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://scientific-python.org/specs/spec-0001/
  summary: Easily load subpackages and functions on demand
  dev_url: https://github.com/scientific-python/lazy-loader
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  description: |
    `lazy-loader` makes it easy to load subpackages and functions on demand.

    PyPI: [https://pypi.org/project/lazy_loader/](https://pypi.org/project/lazy_loader/)

  doc_url: https://github.com/scientific-python/lazy_loader
extra:
  recipe-maintainers:
    - sugatoray
    - bmcfee
